{% set name = "detox" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dharple/detox/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8e37236f9aa2c344181ef62184518e8aafa8f4b1f5013e35cf0787350f957c1

build:
  skip: true  # [win]
  script: ./configure --prefix=${PREFIX} && make install
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make

test:
  commands:
    - detox --help

about:
  home: https://github.com/dharple/detox
  summary: 'Tames problematic filenames'
  description: |
    detox is a program that renames files to make them easier to work with
    under Unix and related operating systems. Spaces and various other unsafe
    characters (such as "$") get replaced with "_". ISO 8859-1 (Latin-1)
    characters can be transliterated to ASCII, as can UTF-8 characters.
    More details are contained in the detox.1 man page.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
